# Generated by Django 6.0.5 on 2026-08-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="address",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="title",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="working_hours",
        ),
        migrations.AddField(
            model_name="contact",
            name="message",
            field=models.TextField(blank=True, verbose_name="Сообщение"),
        ),
        migrations.AddField(
            model_name="contact",
            name="name",
            field=models.CharField(default="", max_length=200, verbose_name="Имя"),
            preserve_default=False,
        ),
    ]
